## 0. 파이토치 : 개요

In [1]:
import torch

### GPU 사용 여부 체크하기

In [2]:
data = [
  [1, 2],
  [3, 4]
]

x = torch.tensor(data)
print(x.is_cuda)

x = x.cuda()
print(x.is_cuda)

x = x.cpu()
print(x.is_cuda)

False
True
False


In [3]:
a = torch.tensor([
    [1, 1],
    [2, 2]
]).cuda()


b = torch.tensor([
    [5, 6],
    [7, 8]
])

'''
# error
print(torch.matmul(a, b))
'''

print(torch.matmul(a.cpu(), b))

tensor([[12, 14],
        [24, 28]])


## 1. 파이토치 : 텐서 소개 및 생성 방법

### 텐서의 속성

In [4]:
tensor = torch.rand(3, 4)

print(tensor)
print(f"Shape: {tensor.shape}")
print(f"Data type: {tensor.dtype}")
print(f"Device: {tensor.device}")

tensor([[0.6523, 0.2426, 0.9140, 0.2377],
        [0.4259, 0.6629, 0.1605, 0.0902],
        [0.1564, 0.5172, 0.8893, 0.8950]])
Shape: torch.Size([3, 4])
Data type: torch.float32
Device: cpu


### 텐서 초기화

In [5]:
data = [
  [1, 2],
  [3, 4]
]
x = torch.tensor(data)

print(x)

tensor([[1, 2],
        [3, 4]])


In [6]:
a = torch.tensor([5])
b = torch.tensor([7])

c = (a + b).numpy()
print(c)
print(type(c))

result = c * 10
tensor = torch.from_numpy(result)
print(tensor)
print(type(tensor))

[12]
<class 'numpy.ndarray'>
tensor([120])
<class 'torch.Tensor'>


### 다른 텐서로부터 텐서 초기화

In [8]:
x = torch.tensor([
    [5, 7],
    [1, 2]
])

x_ones = torch.ones_like(x)
print(x_ones)

x_rand = torch.rand_like(x, dtype=torch.float32)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6642, 0.6477],
        [0.9693, 0.5003]])


## 2. 텐서의 형변환 및 차원 조작

### 텐서의 특정 차원 접근하기

In [15]:
tensor = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(tensor[0])
print(tensor[:, 0])
print(tensor[..., -1])
print(tensor[:,-1])

tensor([1, 2, 3, 4])
tensor([1, 5, 9])
tensor([ 4,  8, 12])
tensor([ 4,  8, 12])


### 텐서 이어붙이기(Concatenate)

In [11]:
tensor = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

result = torch.cat([tensor, tensor, tensor], dim=0)
print(result)

result = torch.cat([tensor, tensor, tensor], dim=1)
print(result)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])


### 텐서 형변환(Type Casting)

In [12]:
a = torch.tensor([2], dtype=torch.int)
b = torch.tensor([5.0])

print(a.dtype)
print(b.dtype)


print(a + b)
print(a + b.type(torch.int32))

torch.int32
torch.float32
tensor([7.])
tensor([7], dtype=torch.int32)


### 텐서의 모양 변경

In [13]:
a = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
b = a.view(4, 2)
print(b)

a[0] = 7
print(b)

c = a.clone().view(4, 2)
a[0] = 9
print(c)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### 텐서의 차원 교환

In [19]:
a = torch.rand((4, 3, 2))
print(a.shape)
print(a)

b = a.permute(2, 1, 0)
print(b.shape)
print(b)

torch.Size([4, 3, 2])
tensor([[[0.0801, 0.2613],
         [0.1057, 0.2195],
         [0.9044, 0.4416]],

        [[0.0753, 0.2796],
         [0.8647, 0.1932],
         [0.6740, 0.5349]],

        [[0.5492, 0.7885],
         [0.9524, 0.3395],
         [0.2912, 0.7256]],

        [[0.3869, 0.8098],
         [0.4191, 0.4205],
         [0.8702, 0.1121]]])
torch.Size([2, 3, 4])
tensor([[[0.0801, 0.0753, 0.5492, 0.3869],
         [0.1057, 0.8647, 0.9524, 0.4191],
         [0.9044, 0.6740, 0.2912, 0.8702]],

        [[0.2613, 0.2796, 0.7885, 0.8098],
         [0.2195, 0.1932, 0.3395, 0.4205],
         [0.4416, 0.5349, 0.7256, 0.1121]]])


## 3. 파이토치 : 텐서의 연산과 함수

### 텐서의 연산

In [32]:
a = torch.tensor([
    [1, 2],
    [3, 4]
])
b = torch.tensor([
    [5, 6],
    [7, 8]
])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [21]:
a = torch.tensor([
    [1, 2],
    [3, 4]
])
b = torch.tensor([
    [5, 6],
    [7, 8]
])

print(a.matmul(b))
print(torch.matmul(a, b))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


### 텐서의 평균 함수

In [22]:
a = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(a)
print(a.mean())
print(a.mean(dim=0))
print(a.mean(dim=1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(4.5000)
tensor([3., 4., 5., 6.])
tensor([2.5000, 6.5000])


### 텐서의 합계 함수

In [23]:
a = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(a)
print(a.sum())
print(a.sum(dim=0))
print(a.sum(dim=1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(36.)
tensor([ 6.,  8., 10., 12.])
tensor([10., 26.])


### 텐서의 최대 함수

In [33]:
a = torch.Tensor([
    [1, 6, 3, 8],
    [5, 2, 7, 4]
])

print(a)
print(a.max())
print(a.max(dim=0))
print(a.max(dim=1))
print(a.argmax())
print(a.argmax(dim=0))
print(a.argmax(dim=1))

tensor([[1., 6., 3., 8.],
        [5., 2., 7., 4.]])
tensor(8.)
torch.return_types.max(
values=tensor([5., 6., 7., 8.]),
indices=tensor([1, 0, 1, 0]))
torch.return_types.max(
values=tensor([8., 7.]),
indices=tensor([3, 2]))
tensor(3)
tensor([1, 0, 1, 0])
tensor([3, 2])


### 텐서의 차원 줄이기 혹은 늘리기

In [34]:
a = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(a.shape)

a = a.unsqueeze(0)
print(a)
print(a.shape)

a = a.unsqueeze(2)
print(a)
print(a.shape)

a = a.squeeze()
print(a)
print(a.shape)

torch.Size([2, 4])
tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
torch.Size([1, 2, 4])
tensor([[[[1., 2., 3., 4.]],

         [[5., 6., 7., 8.]]]])
torch.Size([1, 2, 1, 4])
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])


## 4. 파이토치 : 자동 미분과 기울기

### 연산에 대한 자동 미분

In [38]:
import torch

x = torch.tensor([3.0, 4.0], requires_grad=True)
y = torch.tensor([1.0, 2.0], requires_grad=True)

z = x + y

print(z)
print(z.grad_fn)

out = z.mean()

print(out)
print(out.grad_fn)

out.backward()
print(x.grad)
print(y.grad)
print(z.grad)

tensor([4., 6.], grad_fn=<AddBackward0>)
tensor(5., grad_fn=<MeanBackward0>)
tensor([0.5000, 0.5000])
tensor([0.5000, 0.5000])
None


<ipython-input-38-793454facd6b>:19: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  print(z.grad)


In [36]:
temp = torch.tensor([3.0, 4.0], requires_grad=True)
print(temp.requires_grad)
print((temp ** 2).requires_grad)

with torch.no_grad():
    temp = torch.tensor([3.0, 4.0], requires_grad=True)
    print(temp.requires_grad)
    print((temp ** 2).requires_grad)

True
True
True
False
